"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { seedState } from "@/data/seed";
import { formatDate, formatFullDate, inclusiveDays, isoToday, statusFor } from "@/lib/rules";
import { decodeState, encodeState } from "@/lib/share";
import type { Region, TrackerState, Trip } from "@/lib/types";
import { CalendarPlanner } from "@/components/calendar-planner";
import "./planner.css";
import "./undo.css";
import "./annual-planner.css";

type Tab = "calendar" | "history" | "more";
const TABS = [["calendar", "Calendário", "□"], ["history", "Histórico", "▦"], ["more", "Mais", "☷"]] as const;
type ToastState = { message: string; undo?: { label: string; action: () => void } };

function TripRow({ trip, onClick }: { trip: Trip; onClick: () => void }) {
  const count = inclusiveDays(trip.start, trip.end);
  return <button className="trip-row" onClick={onClick}><span className={"region-marker " + trip.region} /><span className="trip-dates"><strong>{formatDate(trip.start, { day: "2-digit", month: "short" })} — {formatDate(trip.end, { day: "2-digit", month: "short", year: "numeric" })}</strong><small>{trip.country} · {count} {count === 1 ? "dia" : "dias"}</small></span><span className="row-chevron">→</span></button>;
}
function EmptyState({ onAdd }: { onAdd: () => void }) { return <div className="empty-state"><div className="empty-icon">□</div><h3>Nenhuma viagem planejada</h3><p>Registre uma entrada e uma saída para começar a acompanhar seus dias.</p><button className="button primary" onClick={onAdd}>＋ Adicionar viagem</button></div>; }

export default function Home() {
  const [tab, setTab] = useState<Tab>("calendar"); const [state, setState] = useState<TrackerState>(seedState); const [hydrated, setHydrated] = useState(false); const [toast, setToast] = useState<ToastState | null>(null); const [editing, setEditing] = useState<Trip | null | false>(false); const toastTimer = useRef<number | null>(null); const today = isoToday();
  useEffect(() => { const shared = window.location.hash ? decodeState(window.location.hash.slice(1)) : null; const saved = window.localStorage.getItem("staywise-state-v2"); const next = shared || (saved ? decodeState(saved) : null); window.queueMicrotask(() => { if (next) setState(next); setHydrated(true); }); }, []);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "auto" }); }, [tab]);
  useEffect(() => { if (editing === false) return; const close = (event: KeyboardEvent) => { if (event.keyCode === 27) setEditing(false); }; const focusTimer = window.setTimeout(() => window.document.querySelector<HTMLElement>('[role="dialog"] button')?.focus(), 0); window.addEventListener("keydown", close); return () => { window.clearTimeout(focusTimer); window.removeEventListener("keydown", close); }; }, [editing]);
  useEffect(() => { if (hydrated) window.localStorage.setItem("staywise-state-v2", encodeState(state)); }, [state, hydrated]);
  const statuses = useMemo(() => state.rules.map((rule) => statusFor(rule, state.trips, today)), [state, today]); const trips = useMemo(() => state.trips.slice().sort((a, b) => b.start.localeCompare(a.start)), [state.trips]); const risk = statuses.find((item) => item.status === "over") || statuses.find((item) => item.status === "warning");
  function notify(message: string, undo?: ToastState["undo"]) { if (toastTimer.current) window.clearTimeout(toastTimer.current); setToast({ message, undo }); toastTimer.current = window.setTimeout(() => setToast(null), 5000); }
  async function share() { const encoded = encodeState(state); window.history.replaceState(null, "", "#" + encoded); const url = window.location.origin + window.location.pathname + "#" + encoded; await navigator.clipboard?.writeText(url); notify("Link privado copiado"); }
  function exportBackup() { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(state, null, 2)], { type: "application/json" })); link.download = "staywise-backup.json"; link.click(); notify("Backup exportado"); }
  function saveTrip(trip: Trip) { const previous = state; const exists = state.trips.some((item) => item.id === trip.id); const next = { ...state, trips: exists ? state.trips.map((item) => item.id === trip.id ? trip : item) : state.trips.concat(trip) }; const overlaps = state.trips.some((item) => item.id !== trip.id && item.region === trip.region && item.start <= trip.end && item.end >= trip.start); setState(next); setEditing(false); notify(overlaps ? "Viagem salva — há sobreposição com outro período" : "Viagem salva", { label: "Desfazer", action: () => setState(previous) }); }
  function removeTrip(id: string) { const previous = state; setState({ ...state, trips: state.trips.filter((trip) => trip.id !== id) }); setEditing(false); notify("Viagem removida", { label: "Desfazer", action: () => setState(previous) }); }
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">S</span><span>staywise</span></div><div className="topbar-actions"><span className="sync-label"><i className="sync-dot" />Salvo neste dispositivo</span><button className="icon-button" aria-label="Criar link privado" onClick={share}>↗</button></div></header><main className="content-wrap"><section className="welcome"><div><p className="eyebrow">SEU CONTROLE DE DIAS</p><h1>Olá, Andrew.</h1><p className="welcome-copy">Escolha as datas. O Staywise faz as contas.</p></div><div className="today-chip">{formatFullDate(today)}</div></section>{risk && <button className={"alert-banner " + risk.status} onClick={() => setTab("calendar")}><span className="alert-icon">!</span><span><strong>{risk.rule.label}: {risk.status === "over" ? "limite ultrapassado" : "perto do limite"}</strong><small>{risk.used} de {risk.rule.limit} dias usados.</small></span><b>→</b></button>}<div className="tab-panel">{TABS.map(([id, label, icon]) => <button key={id} aria-current={tab === id ? "page" : undefined} className={"tab " + (tab === id ? "active" : "")} onClick={() => setTab(id)}><span className="tab-icon">{icon}</span>{label}</button>)}</div>{tab === "calendar" && <CalendarPlanner trips={trips} rules={state.rules} onOpen={setEditing} onSave={saveTrip} />}{tab === "history" && <HistoryView trips={trips} onOpen={setEditing} onGoCalendar={() => setTab("calendar")} />}{tab === "more" && <Settings state={state} onChange={setState} onShare={share} onExport={exportBackup} />}</main><nav className="bottom-nav">{TABS.map(([id, label, icon]) => <button key={id} aria-current={tab === id ? "page" : undefined} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><span>{icon}</span>{label}</button>)}</nav>{editing !== false && <TripModal trip={editing} onClose={() => setEditing(false)} onSave={saveTrip} onDelete={editing ? removeTrip : undefined} />}{toast && <div className="toast" role="status"><span>✓ {toast.message}</span>{toast.undo && <button className="toast-undo" onClick={() => { toast.undo?.action(); setToast(null); }}>Desfazer</button>}</div>}</div>;
}

function HistoryView({ trips, onOpen, onGoCalendar }: { trips: Trip[]; onOpen: (trip: Trip) => void; onGoCalendar: () => void }) { return <div className="view-stack"><div className="section-heading"><div><p className="eyebrow">HISTÓRICO</p><h2>Suas viagens</h2><p className="section-subtitle">Toque em um período para corrigir ou revisar.</p></div><button className="button primary" onClick={onGoCalendar}>Planejar viagem</button></div><div className="history-summary"><strong>{trips.length}</strong><span>períodos registrados</span></div>{trips.length ? <div className="trip-list">{trips.map((trip) => <TripRow key={trip.id} trip={trip} onClick={() => onOpen(trip)} />)}</div> : <EmptyState onAdd={onGoCalendar} />}</div>; }

function Settings({ state, onChange, onShare, onExport }: { state: TrackerState; onChange: (state: TrackerState) => void; onShare: () => void; onExport: () => void }) { return <div className="view-stack"><div className="section-heading"><div><p className="eyebrow">OPÇÕES</p><h2>Mais</h2></div></div><section className="settings-section"><div className="settings-heading"><h3>Regras de permanência</h3><p>Edite os limites somente se sua orientação profissional usar outros parâmetros.</p></div>{state.rules.map((rule) => <div className="rule-setting" key={rule.id}><div><strong>{rule.label}</strong><span>Limite / janela em dias</span></div><div className="setting-inputs"><label><span>Limite</span><input type="number" value={rule.limit} onChange={(event) => onChange({ ...state, rules: state.rules.map((item) => item.id === rule.id ? { ...item, limit: Number(event.target.value) } : item) })} /></label><b>/</b><label><span>Janela</span><input type="number" value={rule.windowDays} onChange={(event) => onChange({ ...state, rules: state.rules.map((item) => item.id === rule.id ? { ...item, windowDays: Number(event.target.value) } : item) })} /></label></div></div>)}</section><section className="settings-section"><div className="settings-heading"><h3>Compartilhar ou guardar</h3><p>O link carrega os dados no navegador. Quem tiver o link poderá acessar o workspace.</p></div><div className="settings-actions"><button className="button secondary" onClick={onShare}>↗ Criar link privado</button><button className="button secondary" onClick={onExport}>↓ Guardar backup</button></div></section><section className="legal-note"><strong>Sobre o cálculo</strong><p>O app conta dias registrados. Residência fiscal, imigração e obrigações tributárias podem depender de outros fatos.</p></section></div>; }

function TripModal({ trip, onClose, onSave, onDelete }: { trip: Trip | null; onClose: () => void; onSave: (trip: Trip) => void; onDelete?: (id: string) => void }) {
  const [region, setRegion] = useState<Region>(trip?.region || "brazil");
  const [country, setCountry] = useState(trip?.country || "Brazil");
  const [start, setStart] = useState(trip?.start || isoToday());
  const [end, setEnd] = useState(trip?.end || isoToday());
  const [notes, setNotes] = useState(trip?.notes || "");
  const invalid = !start || !end || end < start;
  function choose(value: Region) {
    setRegion(value);
    setCountry(value === "brazil" ? "Brazil" : value === "schengen" ? "Italy" : "Other");
  }
  const options: Array<[Region, string]> = [["brazil", "Brasil"], ["schengen", "Schengen"], ["other", "Outro"]];
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="trip-title"><div className="modal-header"><div><p className="eyebrow">{trip ? "EDITAR PERÍODO" : "NOVO PERÍODO"}</p><h2 id="trip-title">Registrar viagem</h2></div><button className="circle-button" onClick={onClose} aria-label="Fechar">×</button></div><div className="modal-fields"><div className="field-group"><label>Região</label><div className="segmented three" role="group" aria-label="Região do período">{options.map(([value, label]) => <button key={value} aria-pressed={region === value} className={"region-option " + value + (region === value ? " selected" : "")} onClick={() => choose(value)}>{label}</button>)}</div></div><div className="field-group"><label htmlFor="trip-country">País</label><input id="trip-country" value={country} onChange={(event) => setCountry(event.target.value)} /></div><div className="date-fields"><div className="field-group"><label htmlFor="trip-start">Entrada</label><input id="trip-start" type="date" value={start} onChange={(event) => setStart(event.target.value)} /></div><div className="field-group"><label htmlFor="trip-end">Saída</label><input id="trip-end" type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></div></div><div className="field-group"><label htmlFor="trip-notes">Observação <span>(opcional)</span></label><textarea id="trip-notes" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Ex.: visita à família" rows={3} /></div>{invalid && <p className="field-error" role="alert">A saída precisa ser igual ou posterior à entrada.</p>}</div><div className="modal-actions">{onDelete && trip && <button className="text-button danger-text" onClick={() => onDelete(trip.id)}>Excluir</button>}<span /><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={invalid} onClick={() => onSave({ id: trip?.id || "trip-" + Date.now(), region, country, start, end, notes })}>Salvar período</button></div></section></div>;
}
